# Generated by Django 2.1 on 2019-02-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190220_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(0, '包工'), (1, '工匠')], null=True),
        ),
    ]
