# Generated by Django 2.1 on 2019-02-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='sex',
            field=models.ImageField(blank=True, choices=[(0, '男'), (1, '女')], null=True, upload_to=''),
        ),
    ]
