# Generated by Django 2.1 on 2019-02-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190227_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_phone',
            field=models.ImageField(blank=True, choices=[(0, '显示'), (1, '隐藏')], null=True, upload_to=''),
        ),
    ]
