# Generated by Django 2.1 on 2019-03-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_last_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_phone',
            field=models.IntegerField(blank=True, choices=[(0, '显示'), (1, '隐藏')], null=True),
        ),
    ]
