# Generated by Django 2.1 on 2019-02-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
                ('count', models.IntegerField(verbose_name='总数')),
                ('lose', models.IntegerField(verbose_name='失败')),
                ('success', models.IntegerField(verbose_name='成功')),
                ('province', models.CharField(max_length=20, verbose_name='省份')),
                ('a_type', models.CharField(max_length=10, verbose_name='大类型')),
            ],
            options={
                'verbose_name': '爬取日志',
                'verbose_name_plural': '爬取日志',
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('province', models.CharField(max_length=10, verbose_name='省份')),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(null=True, verbose_name='内容')),
                ('source_url', models.CharField(default='', max_length=200, verbose_name='原文链接')),
                ('publish_time', models.DateTimeField(null=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '招标信息',
                'verbose_name_plural': '招标信息',
            },
        ),
    ]
