# Generated by Django 2.1 on 2019-03-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='爬取时间'),
        ),
    ]
